version: '3'
services:
  db:
    image: postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5433:5433"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: sh -c "rm -f /app/tmp/pids/server.id && rails s"
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db/postgres
      - SECRET_KEY_BASE=123456
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
    depends_on:
      - db

