version: '3'
services:
  db:
    image: postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5433:5433"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    entrypoint: ["/app/docker-entrypoint.sh"]
    # command: bash -c "rails db:migrate assets:precompile && foreman start -f Procfile"
    # command: bash -c "rm -f tmp/pids/server.id && rails db:setup assets:precompile && foreman start -f Procfile"
    command: bash -c "rm -f /app/tmp/pids/server.id && rails db:setup assets:precompile"
    volumes:
      - '.:/app'
    ports:
      - '5000:5000'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db/postgres
    depends_on:
      - db

