# Postgres SQL. Versions 3.8.0 and up are supported.
#   gem install pg -- --with-pg-config=<path to pg_config>
#
#   Ensure the pg gem is defined in your Gemfile
#   gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username:
  password:
  timeout: 5000

development:
  <<: *default
  database: myrubyblog_dev

test:
  <<: *default
  database: myrubyblog_test

production:
  <<: *default
  database: myrubyblog_prod
